# Generated by Django 4.2.1 on 2023-05-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam_app', '0003_alter_userprofile_class_alter_userprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Code',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Position',
            field=models.TextField(null=True),
        ),
    ]
