# Generated by Django 4.2.1 on 2023-05-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam_app', '0004_alter_userprofile_code_alter_userprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Name',
        ),
    ]
